apiVersion: batch/v1
kind: Job
metadata:
  name: wrk-clients
spec:
  completions: 10
  parallelism: 10
  template:
    metadata:
      name: wrk-client
    spec:
      containers:
      - name: wrk-client
        image: williamyeh/wrk
        command: ["/bin/sh"]
        args: ["-c", "wrk -t12 -c400 --d5m http://10.244.0.34"]
      restartPolicy: Never